# frozen_string_literal: true

require "csv"
require "pp"

Anyway.loaders.insert_before(:env, :ssm_parameter_store, SsmConfigLoader)

# Ashley's shitty hack to force secret_key_base into a place where
# Rails::Application.secret_key_base can find it.
# This shouldn't be necessary
ENV['SECRET_KEY_BASE'] = Rails.configuration.x.system.secret_key_base
pp "SECRET_KEY_BASE: #{ENV['SECRET_KEY_BASE']}"

# DMPRoadmap constants
#
# This file is a consolidation of the old custom configuration previously spread
# across the application.rb, branding.yml and the contact_us, devise, recaptcha,
# constants and wicked_pdf initializers
#
# It works in conjunction with the new Rails 5 config/credentials.yml.enc file
# for information on how to use the credentials file see:
#    https://medium.com/cedarcode/rails-5-2-credentials-9b3324851336
#
# This file's name begins with an underscore so that it is processed first and its
# values are available to all other initializers within this directory!
module DMPRoadmap

  class Application < Rails::Application

    # --------------------- #
    # ORGANISATION SETTINGS #
    # --------------------- #

    # Your organisation name, used in various places throught the application
    config.x.organisation.name = Rails.configuration.x.application.organisation_name
    # Your organisation's abbreviation
    config.x.organisation.abbreviation = Rails.configuration.x.application.organisation_abbreviation
    # Your organisation's homepage, used in some of the public facing pages
    config.x.organisation.url = Rails.configuration.x.application.organisation_url
    # Your organisation's legal (official) name - used in the copyright portion of the footer
    config.x.organisation.copywrite_name = Rails.configuration.x.application.organisation_copywrite_name
    # This email is used as the 'from' address for emails generated by the application
    config.x.organisation.email = Rails.configuration.x.application.helpdesk_email
    # This email is used as the 'from' address for the feedback_complete email to users
    config.x.organisation.do_not_reply_email = Rails.configuration.x.application.do_not_reply_email
    # This email is used in email communications
    config.x.organisation.helpdesk_email = Rails.configuration.x.application.helpdesk_email
    # Your organisation's telephone number - used on the contact us page
    config.x.organisation.telephone = Rails.configuration.x.application.organisation_phone
    # Your organisation's address - used on the contact us page
    # rubocop:disable Naming/VariableNumber
    config.x.organisation.address = {
      line_1: Rails.configuration.x.application.organisation_address_line1,
      line_2: Rails.configuration.x.application.organisation_address_line2,
      line_3: Rails.configuration.x.application.organisation_address_line3,
      line_4: Rails.configuration.x.application.organisation_address_line4,
      country: Rails.configuration.x.application.organisation_country
    }
    # rubocop:enable Naming/VariableNumber

    # The Google maps link to your organisation's location - used to display the
    # Google map on the contact us page.
    # To find your organisation's Google maps URL, open maps.google.com, search for
    # your orgnaisation and then click the menu link to the left of the search box,
    # once the menu opens, click the 'share or embed' link and the 'embed' tab on
    # the dialog window that opens. DO NOT place the entire <iframe> tag below, just
    # the address!
    config.x.organisation.google_maps_link = Rails.configuration.x.application.organisation_google_maps_link

    # Uncomment the following line if you want to redirect your users to an
    # organisational contact/help page instead of using the built-in contact_us form
    config.x.organisation.contact_us_url = Rails.configuration.x.application.contact_us_url

    # ------------------- #
    # SHIBBOLETH SETTINGS #
    # ------------------- #

    # Enable shibboleth as an alternative authentication method
    # Requires server configuration and omniauth shibboleth provider configuration
    # See config/initializers/devise.rb
    config.x.shibboleth.enabled = Rails.configuration.x.system.shibboleth_enabled

    # Relative path to Shibboleth SSO Logouts
    config.x.shibboleth.login_url = Rails.configuration.x.system.shibboleth_login_url
    config.x.shibboleth.logout_url = Rails.configuration.x.system.shibboleth_logout_url

    # If this value is set to true your users will be presented with a list of orgs that have a
    # shibboleth identifier in the orgs_identifiers table. If it is set to false (default), the user
    # will be driven out to your federation's discovery service
    #
    # A super admin will also be able to associate orgs with their shibboleth entityIds if this is
    # set to true
    config.x.shibboleth.use_filtered_discovery_service = Rails.configuration.x.system.shibboleth_use_filtered_discovery_service

    # ------- #
    # LOCALES #
    # ------- #

    # The default locale (use the i18n format!)
    config.x.locales.default = Rails.configuration.x.application.locales_default
    # The character that separates a locale's ISO code for i18n. (e.g. `en-GB` or `en`)
    # Changing this value is not recommended!
    config.x.locales.i18n_join_character = Rails.configuration.x.application.locales_i18n_join_character
    # The character that separates a locale's ISO code for Gettext. (e.g. `en_GB` or `en`)
    # Changing this value is not recommended!
    config.x.locales.gettext_join_character = Rails.configuration.x.application.locales_gettext_join_character

    # ---------- #
    # THRESHOLDS #
    # ---------- #

    # Determines the number of links a funder is allowed to add to their template
    config.x.max_number_links_funder = Rails.configuration.x.application.max_number_links_funder
    # Maximum number of links to display for an Org
    config.x.max_number_links_org = Rails.configuration.x.application.max_number_links_org
    # Determines the number of links a funder can add for sample plans for their template
    config.x.max_number_links_sample_plan = Rails.configuration.x.application.max_number_links_sample_plan
    # Determines the maximum number of themes to display per column when an org admin
    # updates a template question or guidance
    config.x.max_number_themes_per_column = Rails.configuration.x.application.max_number_themes_per_column
    # default results per page
    config.x.results_per_page = Rails.configuration.x.application.results_per_page

    # ------------- #
    # PLAN DEFAULTS #
    # ------------- #

    # The default visibility a plan receives when it is created.
    # options: 'privately_visible', 'organisationally_visible' and 'publicly_visibile'
    config.x.plans.default_visibility = Rails.configuration.x.application.plans_default_visibility

    # The percentage of answers that have been filled out that determine if a plan
    # will be marked as complete. Plan completion has implications on whether or
    # not plan visibility settings are editable by the user and whether or not the
    # plan can be submitted for feedback
    config.x.plans.default_percentage_answered = Rails.configuration.x.application.plans_default_percentage_answered

    # Whether or not Super adminis can read all of the user's plans regardless of
    # the plans visibility and whether or not the plan has been shared
    config.x.plans.org_admins_read_all = Rails.configuration.x.application.plans_org_admins_read_all
    # Whether or not Organisational administrators can read all of the user's plans
    # regardless of the plans visibility and whether or not the plan has been shared
    config.x.plans.super_admins_read_all = Rails.configuration.x.application.plans_super_admins_read_all

    # ---------------------------------------------------- #
    # CACHING - all values are in seconds (86400 == 1 Day) #
    # ---------------------------------------------------- #

    # Determines how long to cache results for OrgSelection::SearchService
    config.x.cache.org_selection_expiration = Rails.configuration.x.system.cache_org_selection_expiration
    # Determines how long to cache results for the ResearchProjectsController
    config.x.cache.research_projects_expiration = Rails.configuration.x.system.cache_research_projects_expiration

    # ---------------- #
    # Google Analytics #
    # ---------------- #
    # this is the abbreviation for the installation's root org as set in the org table
    config.x.google_analytics.tracker_root = Rails.configuration.x.system.google_analytics_tracker_root

    # ------------------------------------------------------------------------ #
    # reCAPTCHA - recaptcha appears on the create account and contact us forms #
    # ------------------------------------------------------------------------ #
    config.x.recaptcha.enabled = Rails.configuration.x.system.recaptcha_enabled

    # ----------- #
    # DOI Minting
    # ----------- #
    config.x.allow_doi_minting = Rails.configuration.x.system.doi_minting

  end

end
