# frozen_string_literal: true

# AnywayConfig is a gem that allows you to access any of your configuration variables (regardless of
# which of the various Rails's config value stores you use: ENV variables, /config/*.yml files or
# the encrypted credentials file) in the same way.
#
# See the docs for full details on AnywayConfig: https://github.com/palkan/anyway_config
#
class DmproadmapConfig < Anyway::Config
  #           Rails System Config
  #           ----------------------------
  attr_config :secret_key_base,
              :server_host,
              :port,
              :cookie_key,
              :web_concurrency,
              :rails_log_to_stdout,
              :rails_max_threads,
              :rails_serve_static_files,

              # Database Config
              # ----------------------------
              :database_adapter,
              :database_name,
              :database_pool_size,
              :database_host,
              :database_username,
              :database_password,

              # Devise Config
              # ----------------------------
              # We use the Devise gem to manage security. These salt and pepper values are used
              # to encrpyt user passwords
              #
              # TODO: run `rails secret` and update the `config/initializers/devise.rb` to use that
              #       instead of secret_key_base. Then test login via email+pwd. We may need a rake
              #       task that decrypts/rencrypts all of the passwords in the DB.
              #
              #       Be sure to add :devise_salt to the :required field list below!
              :devise_salt,
              :devise_pepper,

              # Logos/Images Config
              # ----------------------------
              # We use the Dragonfly gem to manage Org logos. It resizes the uploaded image and
              # stores it in the specified S3 bucket
              :dragonfly_aws,
              :dragonfly_bucket,
              :dragonfly_host,
              :dragonfly_root_path,
              :dragonfly_secret,
              :dragonfly_url_scheme,

              # Localization Config
              # ----------------------------
              # The default locale (use the i18n format!)
              :locales_default,
              # The character that separates a locale's ISO code for i18n. (e.g. `en-GB` or `en`)
              # Changing this value is not recommended!
              :locales_i18n_join_character,
              # The character that separates a locale's ISO code for Gettext. (e.g. `en_GB` or `en`)
              # Changing this value is not recommended!
              :locales_gettext_join_character,

              # Application Config
              # ----------------------------
              :name,
              # This email is used as the 'from' address for the feedback_complete email to users
              :do_not_reply_email,
              # This email is used in email communications
              :helpdesk_email,
              # Your organisation name, used in various places throught the application
              :organisation_name,
              # Your organisation's abbreviation
              :organisation_abbreviation,
              # Your organisation's homepage, used in some of the public facing pages
              :organisation_url,
              # Your organisation's legal (official) name - used in the copyright portion of the footer
              :organisation_copywrite_name,
              # This email is used as the 'from' address for emails generated by the application
              :email_from_address,
              # Your organisation's telephone number - used on the contact us page
              :organisation_phone,
              # Your organisation's address - used on the contact us page
              :organisation_address_line1,
              :organisation_address_line2,
              :organisation_address_line3,
              :organisation_address_line4,
              :organisation_country,
              # The Google maps link to your organisation's location - used to display the
              # Google map on the contact us page.
              # To find your organisation's Google maps URL, open maps.google.com, search for
              # your orgnaisation and then click the menu link to the left of the search box,
              # once the menu opens, click the 'share or embed' link and the 'embed' tab on
              # the dialog window that opens. DO NOT place the entire <iframe> tag below, just
              # the address!
              :organisation_google_maps_link,
              # The email suffix that will be used when anonymizing a user account. We are unable to
              # completely remove a user record without orphaning data so we instead anonymize the record
              :archived_accounts_email_suffix,
              # Uncomment the following line if you want to redirect your users to an
              # organisational contact/help page instead of using the built-in contact_us form
              :contact_us_url,
              # The various separator options (e.g. comma, pipes, tabs, etc.)
              :csv_separators,
              # The max page size allowed for responses from the API v1+
              :api_max_page_size,
              # The link to the API wiki page
              :api_documentation_urls,
              # The link to our releases page
              :release_notes_url,
              # The link to our issues/ticketing page
              :issue_list_url,
              # The link to subscribe to our Listserv
              :user_group_subscription_url,
              # The link to the blog's RSS feed
              :blog_rss,
              # The links that display on the welcome page (currently unused in DMPTool)
              :welcome_links,
              # The default user email preferences
              :preferences,
              # Determines the number of links a funder is allowed to add to their template
              :max_number_links_funder,
              # Maximum number of links to display for an Org
              :max_number_links_org,
              # Determines the number of links a funder can add for sample plans for their template
              :max_number_links_sample_plan,
              # Determines the maximum number of themes to display per column when an org admin
              # updates a template question or guidance
              :max_number_themes_per_column,
              # default results per page
              :results_per_page,
              # The default visibility a plan receives when it is created.
              # options: 'privately_visible', 'organisationally_visible' and 'publicly_visibile'
              :plans_default_visibility,
              # The percentage of answers that have been filled out that determine if a plan
              # will be marked as complete. Plan completion has implications on whether or
              # not plan visibility settings are editable by the user and whether or not the
              # plan can be submitted for feedback
              :plans_default_percentage_answered,
              # Whether or not Super adminis can read all of the user's plans regardless of
              # the plans visibility and whether or not the plan has been shared
              :plans_org_admins_read_all,
              # Whether or not Organisational administrators can read all of the user's plans
              # regardless of the plans visibility and whether or not the plan has been shared
              :plans_super_admins_read_all,

              # Determines how long to cache results for OrgSelection::SearchService
              :cache_org_selection_expiration,
              # Determines how long to cache results for the ResearchProjectsController
              :cache_research_projects_expiration,

              # External APIs Config
              # ----------------------------
              # Flag indicating whether or not DMP ID (aka DOI) minting is enabled. DMP IDs
              # are generated via a button on a Plan's Finalize/Publish tab
              :doi_minting,

              # DMPHub is our DMP ID (aka DOI) minting authority. It provide DMP Ids and a
              # basic landing page for our DMP
              :dmphub_active,
              :dmphub_url,
              :dmphub_client_id,
              :dmphub_client_secret,

              # this is the abbreviation for the installation's root org as set in the org table
              :google_analytics_tracker_root,

              # The OpenAire API is used for RDA Metadata Standard question types
              :openaire_active,

              # ORCID - Orcid appears on the user profile page
              :orcid_client_id,
              :orcid_client_secret,
              :orcid_sandbox,

              # reCAPTCHA - recaptcha appears on the create account and contact us forms
              :recaptcha_enabled,
              :recaptcha_site_key,
              :recaptcha_secret_key,

              # Rollbar is used to
              :rollbar_env,
              :rollbar_access_token,

              # Whether or not the Org typeahead boxes should call out to the ROR API
              :ror_active,

              # Enable shibboleth as an alternative authentication method
              # Requires server configuration and omniauth shibboleth provider configuration
              # See config/initializers/devise.rb
              :shibboleth_enabled,
              # Relative path to Shibboleth SSO Log in/outs
              :shibboleth_login_url,
              :shibboleth_logout_url,
              # If this value is set to true your users will be presented with a list of orgs that have a
              # shibboleth identifier in the orgs_identifiers table. If it is set to false (default), the user
              # will be driven out to your federation's discovery service
              #
              # A super admin will also be able to associate orgs with their shibboleth entityIds if this is
              # set to true
              :shibboleth_use_filtered_discovery_service,

              # We use Translation.io to facilitate the translation of the strings in the codebase
              # This is used via rake tasks in the dev environment
              :translation_io_key,

              # Usersnap is a plugin we use on the stage environment that allows users to provide
              # contextual feedback by allowing them to screenshot snippets of the page and provide
              # commentary
              :usersnap_key,

              # Wkhtmltopdf is a C library that we use to genrate PDF documents
              :wkhtmltopdf_path

  required :secret_key_base, :server_host, :port, :cookie_key,
           :database_adapter, :database_host, :database_username,
           :devise_pepper,
           :doi_minting,
           :orcid_client_id, :orcid_client_secret, :orcid_sandbox,
           :recaptcha_enabled,
           :shibboleth_enabled,
           :wkhtmltopdf_path,
           :name, :do_not_reply_email, :helpdesk_email,
           :locales_default,
           :preferences,
           :max_number_links_funder, :max_number_links_org,
           :max_number_links_sample_plan, :max_number_themes_per_column,
           :plans_default_visibility, :plans_default_percentage_answered, :plans_org_admins_read_all,
           :plans_super_admins_read_all,


end
