# frozen_string_literal: true

# Load the Rails application.
require_relative "application"

# Load master_key into ENV
require "uc3-ssm"
require "pp"
if ENV.has_key?('SSM_ROOT_PATH')
  begin
    ssm = Uc3Ssm::ConfigResolver.new
    master_key = ssm.parameter_for_key('master_key')
    ENV['RAILS_MASTER_KEY'] = master_key.chomp unless master_key.nil? or master_key.empty?
  rescue => e
    ActiveSupport::Logger.new($stdout).warn("Could not retrieve master_key from SSM Parameter Store: #{e.full_message}")
  end
end
pp ENV['RAILS_MASTER_KEY']

# Initialize the Rails application.
Rails.application.initialize!

Rails.application.configure do
  # Disable serving static files from the `/public` folder by default since
  # Apache or NGINX already handles this.
  config.public_file_server.enabled = Rails.configuration.x.system.rails_serve_static_files.present?

  # Use a different logger for distributed setups.
  # require 'syslog/logger'
  # config.logger = ActiveSupport::TaggedLogging.new(Syslog::Logger.new 'app-name')
  if Rails.configuration.x.system.rails_log_to_stdout.present?
    logger           = ActiveSupport::Logger.new($stdout)
    logger.formatter = config.log_formatter
    config.logger    = ActiveSupport::TaggedLogging.new(logger)
  end

  # URL host to use within emails generated by the application
  config.action_mailer.default_url_options = { host: Rails.configuration.x.system.server_host }
end

# Used by Rails' routes url_helpers (typically when including a link in an email)
Rails.application.routes.default_url_options[:host] = Rails.configuration.x.system.server_host
